exec /usr/bin/xsettingsd &
exec /usr/bin/xcalib -s 0 ~/Documents/Manuals/Lenovo/x201/thinkpadx201.icc &
exec /usr/bin/trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --alpha 0 --tint 0x073642 --height 22 &
exec /usr/bin/nm-applet &
exec /usr/bin/owncloud &
exec /usr/bin/mpd &
exec /usr/bin/xscreensaver -no-splash &
exec /usr/bin/xmonad
